"""Convert the wide Registrar 'Master Summer Electives' CSV into normalized
MySQL tables (3NF) and write two scripts: schema only, and schema + data.

Usage:  python3 build_normalized.py <registrar.csv>
"""
import csv
import re
import sys

src = sys.argv[1]
SCHEMA_OUT = "summer_electives_schema.sql"
FULL_OUT = "summer_electives_normalized.sql"

with open(src, encoding="utf-8-sig", newline="") as f:
    rows = list(csv.reader(f))
header, data = rows[0], rows[1:]
COURSE_START = 6  # first 6 columns describe the student/enrollment


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + v.replace("\\", "\\\\").replace("'", "''") + "'"


def term_parts(name):
    m = re.fullmatch(r"(\w+) AY(\d{2})-(\d{2})", name)
    if not m:
        sys.exit(f"unexpected term format: {name!r}")
    season, y1, y2 = m.groups()
    return season, f"20{y1}-20{y2}"


# ---- courses: every column header is "CODE+Title" --------------------------
course_ids, course_titles = {}, {}
for col in header[COURSE_START:]:
    code, title = (p.strip() for p in col.split("+", 1))
    course_ids[code] = len(course_ids) + 1
    course_titles[code] = title

students, disciplines, campuses, terms, grades = {}, {}, {}, {}, {}
course_discipline = {}
students_courses = []

for r in data:
    sid, first, last, disc, campus, term = (c.strip() for c in r[:COURSE_START])
    students[int(sid)] = (first, last)
    disciplines.setdefault(disc, len(disciplines) + 1)
    campuses.setdefault(campus, len(campuses) + 1)
    terms.setdefault(term, len(terms) + 1)
    for col, grade in zip(header[COURSE_START:], r[COURSE_START:]):
        grade = grade.strip()
        if not grade:
            continue
        code = col.split("+", 1)[0].strip()
        prev = course_discipline.setdefault(code, disc)
        if prev != disc:
            sys.exit(f"course {code} maps to two disciplines: {prev!r}, {disc!r}")
        grades.setdefault(grade, len(grades) + 1)
        students_courses.append((int(sid), course_ids[code], terms[term],
                                 campuses[campus], grades[grade]))


def inserts(table, cols, values, chunk=500):
    lines = []
    for i in range(0, len(values), chunk):
        part = values[i:i + chunk]
        lines.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n" +
                     ",\n".join("  (" + ", ".join(q(v) for v in row) + ")" for row in part) + ";")
    return "\n".join(lines)


schema = f"""-- =====================================================================
-- SUMMER ELECTIVES - NORMALIZED SCHEMA (3NF)
-- Generated by build_normalized.py from the Registrar's master spreadsheet
-- Source: {len(data)} rows x {len(header)} columns (one column per course)
-- =====================================================================

CREATE DATABASE IF NOT EXISTS summer_electives;
USE summer_electives;

DROP TABLE IF EXISTS students_courses;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS terms;
DROP TABLE IF EXISTS campuses;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS students;

-- ---------- entity / lookup tables ----------

CREATE TABLE students (
    student_id  INT         NOT NULL,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    PRIMARY KEY (student_id)
);

CREATE TABLE disciplines (
    discipline_id  INT          NOT NULL AUTO_INCREMENT,
    discipline     VARCHAR(100) NOT NULL,
    PRIMARY KEY (discipline_id),
    UNIQUE KEY uq_discipline (discipline)
);

CREATE TABLE campuses (
    campus_id  INT          NOT NULL AUTO_INCREMENT,
    campus     VARCHAR(100) NOT NULL,
    PRIMARY KEY (campus_id),
    UNIQUE KEY uq_campus (campus)
);

-- 'Summer AY12-13' split into atomic parts
CREATE TABLE terms (
    term_id        INT         NOT NULL AUTO_INCREMENT,
    season         VARCHAR(10) NOT NULL,   -- 'Summer'
    academic_year  CHAR(9)     NOT NULL,   -- '2012-2013'
    PRIMARY KEY (term_id),
    UNIQUE KEY uq_term (season, academic_year)
);

CREATE TABLE grades (
    grade_id    INT        NOT NULL AUTO_INCREMENT,
    grade_code  VARCHAR(5) NOT NULL,        -- A, B+, P, AU ...
    PRIMARY KEY (grade_id),
    UNIQUE KEY uq_grade_code (grade_code)
);

-- Column header 'MGT-606+Operations Management' -> course_code + course_title.
-- Each course belongs to exactly one discipline (1:M, like shows -> show_types).
-- discipline_id is NULL for courses that nobody took in this extract.
CREATE TABLE courses (
    course_id      INT          NOT NULL AUTO_INCREMENT,
    discipline_id  INT          NULL,
    course_code    VARCHAR(12)  NOT NULL,
    course_title   VARCHAR(100) NOT NULL,
    PRIMARY KEY (course_id),
    UNIQUE KEY uq_course_code (course_code),
    FOREIGN KEY (discipline_id) REFERENCES disciplines (discipline_id)
);

-- ---------- junction table (resolves students M:N courses) ----------
-- Same pattern as shows_artists_roles: the primary key is made only of
-- foreign keys. A student can take the same course again in another term,
-- so term_id is part of the key. campus_id and grade_id describe that one
-- enrollment, so they are ordinary (non-key) foreign-key columns.
CREATE TABLE students_courses (
    student_id  INT NOT NULL,
    course_id   INT NOT NULL,
    term_id     INT NOT NULL,
    campus_id   INT NOT NULL,
    grade_id    INT NOT NULL,
    PRIMARY KEY (student_id, course_id, term_id),
    FOREIGN KEY (student_id) REFERENCES students (student_id),
    FOREIGN KEY (course_id)  REFERENCES courses (course_id),
    FOREIGN KEY (term_id)    REFERENCES terms (term_id),
    FOREIGN KEY (campus_id)  REFERENCES campuses (campus_id),
    FOREIGN KEY (grade_id)   REFERENCES grades (grade_id)
);
"""

data_sql = "\n\n".join([
    "-- ---------------- DATA ----------------",
    inserts("students", ["student_id", "first_name", "last_name"],
            [(k, *v) for k, v in sorted(students.items())]),
    inserts("disciplines", ["discipline_id", "discipline"],
            [(i, n) for n, i in disciplines.items()]),
    inserts("campuses", ["campus_id", "campus"],
            [(i, n) for n, i in campuses.items()]),
    inserts("terms", ["term_id", "season", "academic_year"],
            [(i, *term_parts(n)) for n, i in terms.items()]),
    inserts("grades", ["grade_id", "grade_code"],
            [(i, g) for g, i in grades.items()]),
    inserts("courses", ["course_id", "discipline_id", "course_code", "course_title"],
            [(i, disciplines[course_discipline[c]] if c in course_discipline else None,
              c, course_titles[c]) for c, i in course_ids.items()]),
    inserts("students_courses", ["student_id", "course_id", "term_id", "campus_id", "grade_id"],
            students_courses),
    f"""-- ---------------- CHECKS ----------------
-- Expected: students {len(students)}, courses {len(course_ids)}, students_courses {len(students_courses)}
SELECT 'students' AS tbl, COUNT(*) AS n FROM students
UNION ALL SELECT 'disciplines', COUNT(*) FROM disciplines
UNION ALL SELECT 'campuses', COUNT(*) FROM campuses
UNION ALL SELECT 'terms', COUNT(*) FROM terms
UNION ALL SELECT 'grades', COUNT(*) FROM grades
UNION ALL SELECT 'courses', COUNT(*) FROM courses
UNION ALL SELECT 'students_courses', COUNT(*) FROM students_courses;
"""])

with open(SCHEMA_OUT, "w", encoding="utf-8") as f:
    f.write(schema)
with open(FULL_OUT, "w", encoding="utf-8") as f:
    f.write(schema + "\n\n" + data_sql)
print(f"wrote {SCHEMA_OUT}, {FULL_OUT}: {len(students)} students, {len(course_ids)} courses, "
      f"{len(students_courses)} students_courses rows")
