"""Convert the wide Registrar 'Master Summer Electives' CSV into normalized
MySQL tables (3NF) and write a self-contained load script.

Usage:  python3 build_normalized.py <registrar.csv> [output.sql]
"""
import csv
import re
import sys

src = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else "summer_electives_normalized.sql"

with open(src, encoding="utf-8-sig", newline="") as f:
    rows = list(csv.reader(f))
header, data = rows[0], rows[1:]
COURSE_START = 6  # first 6 columns describe the student/enrollment

GRADE_INFO = {  # grade_code -> (description, grade_points or None)
    "A": ("Excellent", 4.0), "A-": ("Excellent", 3.7),
    "B+": ("Good", 3.3), "B": ("Good", 3.0), "B-": ("Good", 2.7),
    "C+": ("Satisfactory", 2.3), "C": ("Satisfactory", 2.0), "C-": ("Satisfactory", 1.7),
    "D": ("Poor", 1.0), "F": ("Fail", 0.0),
    "P": ("Pass", None), "Pass": ("Pass", None), "HP": ("High Pass", None),
    "AU": ("Audit", None), "I": ("Incomplete", None), "W": ("Withdrawn", None),
}


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + v.replace("\\", "\\\\").replace("'", "''") + "'"


# ---- courses: every column header is "CODE+Title" --------------------------
courses = {}
for col in header[COURSE_START:]:
    code, title = col.split("+", 1)
    courses[code.strip()] = title.strip()

students, disciplines, campuses, terms = {}, {}, {}, {}
course_discipline = {}
grades_used = set()
enrollments = []

for r in data:
    sid, first, last, disc, campus, term = (c.strip() for c in r[:COURSE_START])
    students[int(sid)] = (first, last)
    disciplines.setdefault(disc, len(disciplines) + 1)
    campuses.setdefault(campus, len(campuses) + 1)
    terms.setdefault(term, len(terms) + 1)
    for col, grade in zip(header[COURSE_START:], r[COURSE_START:]):
        grade = grade.strip()
        if not grade:
            continue
        code = col.split("+", 1)[0].strip()
        prev = course_discipline.setdefault(code, disc)
        if prev != disc:
            sys.exit(f"course {code} maps to two disciplines: {prev!r}, {disc!r}")
        grades_used.add(grade)
        enrollments.append((int(sid), code, terms[term], campuses[campus], grade))

unknown = grades_used - GRADE_INFO.keys()
if unknown:
    sys.exit(f"unmapped grade codes: {sorted(unknown)}")


def term_parts(name):
    m = re.fullmatch(r"(\w+) AY(\d{2})-(\d{2})", name)
    if not m:
        sys.exit(f"unexpected term format: {name!r}")
    season, y1, y2 = m.groups()
    return season, f"20{y1}-20{y2}", 2000 + int(y1)


def inserts(table, cols, values, chunk=500):
    lines = []
    for i in range(0, len(values), chunk):
        part = values[i:i + chunk]
        lines.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n" +
                     ",\n".join("  (" + ", ".join(q(v) for v in row) + ")" for row in part) + ";")
    return "\n".join(lines)


sql = [f"""-- =====================================================================
-- SUMMER ELECTIVES - NORMALIZED SCHEMA (3NF) + DATA
-- Generated by build_normalized.py from the Registrar's master spreadsheet
-- Source: {len(data)} rows x {len(header)} columns (wide / one column per course)
-- Result: {len(students)} students, {len(courses)} courses, {len(enrollments)} enrollments
-- =====================================================================

CREATE DATABASE IF NOT EXISTS summer_electives;
USE summer_electives;

DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS term;
DROP TABLE IF EXISTS campus;
DROP TABLE IF EXISTS discipline;
DROP TABLE IF EXISTS student;

-- One row per student (name depends only on student_id)
CREATE TABLE student (
    student_id   INT          NOT NULL,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (student_id)
);

-- Lookup: subject area a course belongs to
CREATE TABLE discipline (
    discipline_id    INT          NOT NULL AUTO_INCREMENT,
    discipline_name  VARCHAR(100) NOT NULL,
    PRIMARY KEY (discipline_id),
    UNIQUE KEY uq_discipline_name (discipline_name)
);

-- Lookup: where the course was taken
CREATE TABLE campus (
    campus_id    INT          NOT NULL AUTO_INCREMENT,
    campus_name  VARCHAR(100) NOT NULL,
    PRIMARY KEY (campus_id),
    UNIQUE KEY uq_campus_name (campus_name)
);

-- Lookup: 'Summer AY12-13' split into atomic parts
CREATE TABLE term (
    term_id         INT         NOT NULL AUTO_INCREMENT,
    term_name       VARCHAR(30) NOT NULL,   -- original label, e.g. 'Summer AY12-13'
    season          VARCHAR(10) NOT NULL,   -- 'Summer'
    academic_year   CHAR(9)     NOT NULL,   -- '2012-2013'
    start_year      SMALLINT    NOT NULL,   -- 2012 (handy for sorting)
    PRIMARY KEY (term_id),
    UNIQUE KEY uq_term_name (term_name)
);

-- Lookup: valid grade codes
CREATE TABLE grade (
    grade_code    VARCHAR(5)   NOT NULL,
    description   VARCHAR(30)  NOT NULL,
    grade_points  DECIMAL(2,1) NULL,        -- NULL = not GPA-bearing (Pass, Audit, ...)
    PRIMARY KEY (grade_code)
);

-- One row per course; the column header 'MGT-606+Operations Management'
-- becomes course_code + course_title. discipline_id is NULL for courses
-- that appear as a column but nobody took in this extract.
CREATE TABLE course (
    course_code    VARCHAR(12)  NOT NULL,
    course_title   VARCHAR(100) NOT NULL,
    subject_code   VARCHAR(5)   NOT NULL,   -- prefix, e.g. 'MGT'
    discipline_id  INT          NULL,
    PRIMARY KEY (course_code),
    FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)
);

-- Fact table: one row per student per course per term (one grade cell of the sheet)
CREATE TABLE enrollment (
    enrollment_id  INT         NOT NULL AUTO_INCREMENT,
    student_id     INT         NOT NULL,
    course_code    VARCHAR(12) NOT NULL,
    term_id        INT         NOT NULL,
    campus_id      INT         NOT NULL,
    grade_code     VARCHAR(5)  NOT NULL,
    PRIMARY KEY (enrollment_id),
    UNIQUE KEY uq_student_course_term (student_id, course_code, term_id),
    FOREIGN KEY (student_id)  REFERENCES student (student_id),
    FOREIGN KEY (course_code) REFERENCES course (course_code),
    FOREIGN KEY (term_id)     REFERENCES term (term_id),
    FOREIGN KEY (campus_id)   REFERENCES campus (campus_id),
    FOREIGN KEY (grade_code)  REFERENCES grade (grade_code)
);
"""]

sql.append("-- ---------------- DATA ----------------")
sql.append(inserts("student", ["student_id", "first_name", "last_name"],
                   [(k, *v) for k, v in sorted(students.items())]))
sql.append(inserts("discipline", ["discipline_id", "discipline_name"],
                   [(i, n) for n, i in disciplines.items()]))
sql.append(inserts("campus", ["campus_id", "campus_name"],
                   [(i, n) for n, i in campuses.items()]))
sql.append(inserts("term", ["term_id", "term_name", "season", "academic_year", "start_year"],
                   [(i, n, *term_parts(n)) for n, i in terms.items()]))
sql.append(inserts("grade", ["grade_code", "description", "grade_points"],
                   [(g, *GRADE_INFO[g]) for g in GRADE_INFO]))
sql.append(inserts("course", ["course_code", "course_title", "subject_code", "discipline_id"],
                   [(c, t, c.split("-")[0],
                     disciplines[course_discipline[c]] if c in course_discipline else None)
                    for c, t in sorted(courses.items())]))
sql.append(inserts("enrollment", ["student_id", "course_code", "term_id", "campus_id", "grade_code"],
                   enrollments))

sql.append(f"""
-- ---------------- CHECKS ----------------
-- Expected: student {len(students)}, course {len(courses)}, enrollment {len(enrollments)}
SELECT 'student' AS tbl, COUNT(*) AS n FROM student
UNION ALL SELECT 'discipline', COUNT(*) FROM discipline
UNION ALL SELECT 'campus', COUNT(*) FROM campus
UNION ALL SELECT 'term', COUNT(*) FROM term
UNION ALL SELECT 'grade', COUNT(*) FROM grade
UNION ALL SELECT 'course', COUNT(*) FROM course
UNION ALL SELECT 'enrollment', COUNT(*) FROM enrollment;
""")

with open(out, "w", encoding="utf-8") as f:
    f.write("\n\n".join(sql))
print(f"wrote {out}: {len(students)} students, {len(courses)} courses, "
      f"{len(enrollments)} enrollments, {len(disciplines)} disciplines, "
      f"{len(campuses)} campuses, {len(terms)} terms, grades used {sorted(grades_used)}")
