-- =====================================================================
-- SUMMER ELECTIVES - NORMALIZED SCHEMA (3NF)
-- Generated by build_normalized.py from the Registrar's master spreadsheet
-- Source: 998 rows x 650 columns (one column per course)
-- =====================================================================

CREATE DATABASE IF NOT EXISTS summer_electives;
USE summer_electives;

DROP TABLE IF EXISTS students_courses;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS terms;
DROP TABLE IF EXISTS campuses;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS students;

-- ---------- entity / lookup tables ----------

CREATE TABLE students (
    student_id  INT         NOT NULL,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    PRIMARY KEY (student_id)
);

CREATE TABLE disciplines (
    discipline_id  INT          NOT NULL AUTO_INCREMENT,
    discipline     VARCHAR(100) NOT NULL,
    PRIMARY KEY (discipline_id),
    UNIQUE KEY uq_discipline (discipline)
);

CREATE TABLE campuses (
    campus_id  INT          NOT NULL AUTO_INCREMENT,
    campus     VARCHAR(100) NOT NULL,
    PRIMARY KEY (campus_id),
    UNIQUE KEY uq_campus (campus)
);

-- 'Summer AY12-13' split into atomic parts
CREATE TABLE terms (
    term_id        INT         NOT NULL AUTO_INCREMENT,
    season         VARCHAR(10) NOT NULL,   -- 'Summer'
    academic_year  CHAR(9)     NOT NULL,   -- '2012-2013'
    PRIMARY KEY (term_id),
    UNIQUE KEY uq_term (season, academic_year)
);

CREATE TABLE grades (
    grade_id    INT        NOT NULL AUTO_INCREMENT,
    grade_code  VARCHAR(5) NOT NULL,        -- A, B+, P, AU ...
    PRIMARY KEY (grade_id),
    UNIQUE KEY uq_grade_code (grade_code)
);

-- Column header 'MGT-606+Operations Management' -> course_code + course_title.
-- Each course belongs to exactly one discipline (1:M, like shows -> show_types).
-- discipline_id is NULL for courses that nobody took in this extract.
CREATE TABLE courses (
    course_id      INT          NOT NULL AUTO_INCREMENT,
    discipline_id  INT          NULL,
    course_code    VARCHAR(12)  NOT NULL,
    course_title   VARCHAR(100) NOT NULL,
    PRIMARY KEY (course_id),
    UNIQUE KEY uq_course_code (course_code),
    FOREIGN KEY (discipline_id) REFERENCES disciplines (discipline_id)
);

-- ---------- junction table (resolves students M:N courses) ----------
-- Same pattern as shows_artists_roles: the primary key is made only of
-- foreign keys. A student can take the same course again in another term,
-- so term_id is part of the key. campus_id and grade_id describe that one
-- enrollment, so they are ordinary (non-key) foreign-key columns.
CREATE TABLE students_courses (
    student_id  INT NOT NULL,
    course_id   INT NOT NULL,
    term_id     INT NOT NULL,
    campus_id   INT NOT NULL,
    grade_id    INT NOT NULL,
    PRIMARY KEY (student_id, course_id, term_id),
    FOREIGN KEY (student_id) REFERENCES students (student_id),
    FOREIGN KEY (course_id)  REFERENCES courses (course_id),
    FOREIGN KEY (term_id)    REFERENCES terms (term_id),
    FOREIGN KEY (campus_id)  REFERENCES campuses (campus_id),
    FOREIGN KEY (grade_id)   REFERENCES grades (grade_id)
);
