-- =====================================================================
-- SUMMER ELECTIVES - NORMALIZED SCHEMA (3NF) + DATA
-- Generated by build_normalized.py from the Registrar's master spreadsheet
-- Source: 998 rows x 650 columns (wide / one column per course)
-- Result: 423 students, 644 courses, 1182 enrollments
-- =====================================================================

CREATE DATABASE IF NOT EXISTS summer_electives;
USE summer_electives;

DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS term;
DROP TABLE IF EXISTS campus;
DROP TABLE IF EXISTS discipline;
DROP TABLE IF EXISTS student;

-- One row per student (name depends only on student_id)
CREATE TABLE student (
    student_id   INT          NOT NULL,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (student_id)
);

-- Lookup: subject area a course belongs to
CREATE TABLE discipline (
    discipline_id    INT          NOT NULL AUTO_INCREMENT,
    discipline_name  VARCHAR(100) NOT NULL,
    PRIMARY KEY (discipline_id),
    UNIQUE KEY uq_discipline_name (discipline_name)
);

-- Lookup: where the course was taken
CREATE TABLE campus (
    campus_id    INT          NOT NULL AUTO_INCREMENT,
    campus_name  VARCHAR(100) NOT NULL,
    PRIMARY KEY (campus_id),
    UNIQUE KEY uq_campus_name (campus_name)
);

-- Lookup: 'Summer AY12-13' split into atomic parts
CREATE TABLE term (
    term_id         INT         NOT NULL AUTO_INCREMENT,
    term_name       VARCHAR(30) NOT NULL,   -- original label, e.g. 'Summer AY12-13'
    season          VARCHAR(10) NOT NULL,   -- 'Summer'
    academic_year   CHAR(9)     NOT NULL,   -- '2012-2013'
    start_year      SMALLINT    NOT NULL,   -- 2012 (handy for sorting)
    PRIMARY KEY (term_id),
    UNIQUE KEY uq_term_name (term_name)
);

-- Lookup: valid grade codes
CREATE TABLE grade (
    grade_code    VARCHAR(5)   NOT NULL,
    description   VARCHAR(30)  NOT NULL,
    grade_points  DECIMAL(2,1) NULL,        -- NULL = not GPA-bearing (Pass, Audit, ...)
    PRIMARY KEY (grade_code)
);

-- One row per course; the column header 'MGT-606+Operations Management'
-- becomes course_code + course_title. discipline_id is NULL for courses
-- that appear as a column but nobody took in this extract.
CREATE TABLE course (
    course_code    VARCHAR(12)  NOT NULL,
    course_title   VARCHAR(100) NOT NULL,
    subject_code   VARCHAR(5)   NOT NULL,   -- prefix, e.g. 'MGT'
    discipline_id  INT          NULL,
    PRIMARY KEY (course_code),
    FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)
);

-- Fact table: one row per student per course per term (one grade cell of the sheet)
CREATE TABLE enrollment (
    enrollment_id  INT         NOT NULL AUTO_INCREMENT,
    student_id     INT         NOT NULL,
    course_code    VARCHAR(12) NOT NULL,
    term_id        INT         NOT NULL,
    campus_id      INT         NOT NULL,
    grade_code     VARCHAR(5)  NOT NULL,
    PRIMARY KEY (enrollment_id),
    UNIQUE KEY uq_student_course_term (student_id, course_code, term_id),
    FOREIGN KEY (student_id)  REFERENCES student (student_id),
    FOREIGN KEY (course_code) REFERENCES course (course_code),
    FOREIGN KEY (term_id)     REFERENCES term (term_id),
    FOREIGN KEY (campus_id)   REFERENCES campus (campus_id),
    FOREIGN KEY (grade_code)  REFERENCES grade (grade_code)
);


